#
#Wed Oct 04 10:57:18 CEST 2017
Report.snticket=Ticket number
Report.title=Remediation synthesis for <VALUE-OF>params["repository"].value</VALUE-OF>
Report.on=on
Report.accountremediation=Revoked accounts
Report.by=by
Report.rightremediation=Revoked rights
