Metadata.link.bwa_accountmetadata.metadata=
Metadata.value.bwa_accountmetadata.value4string=description
Metadata.value.bwa_accountmetadata.value4string.search=which
Metadata.value.bwa_accountmetadata.value5string=sensitivity reason
Metadata.value.bwa_accountmetadata.value5string.search=which
Metadata.value.bwa_accountmetadata.value1integer=sensitivity level
Metadata.value.bwa_accountmetadata.value1integer.search=which
Metadata.value.bwa_accountmetadata.valueboolean=sensitivity has been set manually
Metadata.value.bwa_accountmetadata.valueboolean.search=sensitivity has been set automatically
Metadata.link.bwa_groupmetadata.metadata=
Metadata.value.bwa_groupmetadata.value4string=description
Metadata.value.bwa_groupmetadata.value4string.search=which
Metadata.value.bwa_groupmetadata.value5string=sensitivity reason
Metadata.value.bwa_groupmetadata.value5string.search=which
Metadata.value.bwa_groupmetadata.value1integer=sensitivity level
Metadata.value.bwa_groupmetadata.value1integer.search=which
Metadata.value.bwa_groupmetadata.valueboolean=is managed
Metadata.value.bwa_groupmetadata.valueboolean.search=is not managed
Metadata.link.bwa_applicationmetadata.metadata=
Metadata.value.bwa_applicationmetadata.value4string=description
Metadata.value.bwa_applicationmetadata.value4string.search=which
Metadata.value.bwa_applicationmetadata.value5string=sensitivity reason
Metadata.value.bwa_applicationmetadata.value5string.search=which
Metadata.value.bwa_applicationmetadata.value3string=category
Metadata.value.bwa_applicationmetadata.value3string.search=which
Metadata.value.bwa_applicationmetadata.value1integer=sensitivity level
Metadata.value.bwa_applicationmetadata.value1integer.search=which
Metadata.link.bwa_permissionmetadata.metadata=
Metadata.value.bwa_permissionmetadata.value4string=description
Metadata.value.bwa_permissionmetadata.value4string.search=which
Metadata.value.bwa_permissionmetadata.value5string=sensitivity reason
Metadata.value.bwa_permissionmetadata.value5string.search=which
Metadata.value.bwa_permissionmetadata.value1integer=sensitivity level
Metadata.value.bwa_permissionmetadata.value1integer.search=which
Metadata.value.bwa_permissionmetadata.valueboolean=is managed
Metadata.value.bwa_permissionmetadata.valueboolean.search=is not managed
Metadata.link.bwa_repositorymetadata.metadata=
Metadata.value.bwa_repositorymetadata.value4string=description
Metadata.value.bwa_repositorymetadata.value4string.search=which
Metadata.value.bwa_repositorymetadata.value5string=sensitivity reason
Metadata.value.bwa_repositorymetadata.value5string.search=which
Metadata.value.bwa_repositorymetadata.value3string=category
Metadata.value.bwa_repositorymetadata.value3string.search=which
Metadata.value.bwa_repositorymetadata.value1integer=sensitivity level
Metadata.value.bwa_repositorymetadata.value1integer.search=which
Metadata.link.bwa_identitymetadata.metadata=
Metadata.value.bwa_identitymetadata.value4string=description
Metadata.value.bwa_identitymetadata.value4string.search=which
Metadata.value.bwa_identitymetadata.value5string=sensitivity reason
Metadata.value.bwa_identitymetadata.value5string.search=which
Metadata.value.bwa_identitymetadata.value1integer=sensitivity level
Metadata.value.bwa_identitymetadata.value1integer.search=which
Metadata.value.bwa_identitymetadata.valueboolean=sensitivity has been set manually
Metadata.value.bwa_identitymetadata.valueboolean.search=sensitivity has been set automatically
Metadata.link.bwa_organisationmetadata.metadata=
Metadata.value.bwa_organisationmetadata.value4string=description
Metadata.value.bwa_organisationmetadata.value4string.search=which
Metadata.value.bwa_organisationmetadata.value5string=sensitivity reason
Metadata.value.bwa_organisationmetadata.value5string.search=which
Metadata.value.bwa_organisationmetadata.value1integer=sensitivity level
Metadata.value.bwa_organisationmetadata.value1integer.search=which
