Metadata.link.bwa_repositorytags.metadata=
Metadata.value.bwa_repositorytags.value1string=tag
Metadata.value.bwa_repositorytags.value1string.search=which
Metadata.link.bwa_permissiontags.metadata=
Metadata.value.bwa_permissiontags.value1string=tag
Metadata.value.bwa_permissiontags.value1string.search=which
Metadata.link.bwa_organisationtags.metadata=
Metadata.value.bwa_organisationtags.value1string=tag
Metadata.value.bwa_organisationtags.value1string.search=which
Metadata.link.bwa_identitytags.metadata=
Metadata.value.bwa_identitytags.value1string=tag
Metadata.value.bwa_identitytags.value1string.search=which
Metadata.link.bwa_grouptags.metadata=
Metadata.value.bwa_grouptags.value1string=tag
Metadata.value.bwa_grouptags.value1string.search=which
Metadata.link.bwa_applicationtags.metadata=
Metadata.value.bwa_applicationtags.value1string=tag
Metadata.value.bwa_applicationtags.value1string.search=which
Metadata.link.bwa_accounttags.metadata=
Metadata.value.bwa_accounttags.value1string=tag
Metadata.value.bwa_accounttags.value1string.search=which
