#
#Tue Apr 03 19:22:09 CEST 2018
Report.startedworkingon=Started working on
Report.reviewedby=Reviewed by
Report.instancestartedon=Instance started on
Report.instanceclosedate=Instance close date
Report.campaignownedby=Campaign owned by
Report.reviewdoneone=Review done on
Report.campaigninstanceperimeter=Campaign instance perimeter (entities reviewed)
Report.nbentries=Nb entries to review
Report.title=Detail Compliance Report
Report.instancelaunchedby=Instance launched by
Report.campaigntitle=Campaign title
Report.campaigninformation=Campaign information
Report.campaigndescription=Campaign description
Report.campaignidentifier=Campaign identifier
Report.instanceduedate=Instance due date
