#
#Tue Apr 03 17:14:46 CEST 2018
Report.title=Compliance report
Report.campaigninformation=Campaign information
Report.campaignidentifier=Campaign identifier
Report.campaigntitle=Campaign title
Report.campaigndescription=Campaign description
Report.campaignownedby=Campaign owned by
Report.instancestartedon=Instance started on
Report.instanceduedate=Instance due date
Report.instanceclosedate=Instance close date
Report.instancelaunchedby=Instance launched by
Report.campaigninstanceperimeter=Campaign instance perimeter (entities reviewed)
Report.nbentries=Nb entries to review
Report.reviewedby=Reviewed by
Report.startedworkingon=Started working on
Report.reviewdoneone=Review done on
