Domain.concept=Domain
Account.expiredate=Account expiration date
Account.nextpwdchangedate=Next account password change date
Reconciliation.noownercode=Code explaining the lack of owner
Identity.active=Active identity flag
Group.creationdate=Group creation date
Group.modificationdate=Group modification date
Group.nbaccounts=Nb accounts
Account.nbgroups=Nb groups