#
#Thu Feb 06 15:10:43 CET 2025
Report.title=Review Campaign Compliance Report
Review.Status.NotReviewed=Not reviewed
Review.Status.Ok=Approved
Review.Status.Revoke=Revoked
Review.account=Account
Review.campaignactivity=Campaign Activity (\# of reviewed entries per day)
Review.campaigndescription=Campaign Description
Review.campaignid=Campaign Name
Review.campaigntype=Campaign Type
Review.comment=Comment
Review.decisionsynthesis=Decisions Synthesis (\# of entries per status)
Review.duedate=Due Date
Review.generalComment=General Remarks
Review.group=Login / Group 
Review.perimeter=Perimeter (\# of entries)
Review.prioritylevel=Priority Level
Review.reviewedby=Reviewed by
Review.reviewedon=Reviewed on
Review.right=Right
Review.status=Status
Review.submissiondate=Submission Date
Review.ticketnumber=Ticket Number
Review.signofby=Sign-off
Review.campaignmode=Campaign Mode
Review.entry=Reviewed Entry