#
#Fri Dec 05 10:43:07 CET 2025
report.reconcomment=Account Reconciliation Comment
Review.Status.Ok=OK
report.applicationdescription=Application Description
report.reconleavedate=Account Owner Leave Date
report.permissioncode=Permission Code
report.identityfullame=Identity Fullname
Review.campaignactivity=Campaign Activity
Review.decisionsynthesis=Decision Synthesis
report.accountlastlogindate=Account Last Login Date
report.identityhrcode=Identity Employee Number
Review.campaignmode=Campaign Mode
Review.perimeter=Perimeter
report.reviewername=Reviewer Name
Report.title=Title
Review.campaigndescription=Description
Review.signofby=Signed Off By
report.identitydeparturedate=Identity Departure Date
report.permissiondescription=Permission Description
Review.reviewedby=Reviewed By
report.permissionsensitivitylevel=Permission Sensitivity Level
Review.comment=Comment
report.rightperimeter=Access Right Perimeter
report.reconnoownercode=Service Account Code
Review.campaignid=Campaign Id
Review.reviewedon=Reviewed On
Review.group=Group
report.permissiondisplayname=Permission Name
Review.Status.Revoke=Revoke
report.applicationdisplayname=Application
Review.submissiondate=Submission Date
Review.right=Right
report.identityinternal=Identity Internal
Review.account=Account
Review.Status.NotReviewed=Not Reviewed
Review.ticketnumber=Ticket Number
Review.campaigntype=Campaign Type
Review.duedate=Due Date
report.accountlogin=Account Login
report.identityarrivaldate=Identity Arrival Date
Review.status=Status
report.accountusername=Account Username
Review.prioritylevel=Priority level
report.rightlimit=Access Right Limit
report.rightaction=Access Right Allowed Action
report.applicationsensitivitylevel=Application Sensitivity Level
report.identityactive=Identity Active
report.identityjoborg=Identity Job and Organization
report.identitymail=Identity Mail
Review.generalComment=General Comment
report.reviewerorigin=Reviewer Origin
