#
#Mon May 06 14:52:02 CEST 2024
report.identityhrcode=Identity Employee Number
report.reconcomment=Account Reconciliation Comment
report.applicationdisplayname=Application
report.reviewername=Reviewer Name
report.identityinternal=Identity Internal
report.applicationdescription=Application Description
report.reconleavedate=Account Owner Leave Date
report.identityfullame=Identity Fullname
report.applicationsensitivitylevel=Application Sensitivity Level
report.identityactive=Identity Active
report.identitydeparturedate=Identity Departure Date
report.identityjoborg=Identity Job and Organization
report.accountlogin=Account Login
report.identityarrivaldate=Identity Arrival Date
report.identitymail=Identity Mail
report.accountusername=Account Username
report.reconnoownercode=Service Account Code
report.accountlastlogindate=Account Last Login Date
report.reviewerorigin=Reviewer Origin
