Report.title=Application rights latest review status
status=Status
comment=Comment
reviewer=Reviewer
job=Job
task.enddate=Task end date
campaign.code=Campaign code
campaign.descrition=Campaign description
campaign.owner=Campaign owner
campaign.startdate=Start date
campaign.enddate=End date
campaign.type=Type