reviewstatus=Review Status
reviewcomment=Review Comment
reviewerfullname=Reviewer Fullname
reviewerorigin=Reviewer Origin
reviewrecorduid=Review RecordUid
permissioncode=Permission Code
permissionsensitivity=Permission Sensitivity
permissionsensitivitylevel=Permission Sensitivity Level
permissiondescription=Permission Description
applicationsensitivity=Application Sensitivity
applicationsensitivitylevel=Application Sensitivity Level
applicationdescription=Application Description