#
#Thu Nov 02 14:59:12 CET 2023
Report.reconleavdate=Leave Date
Report.grouptype=Group Type
Report.dynamicgroup=Dynamic Group
Report.reviewstatus=Review Status
Report.reviewcomment=Review Comment
Report.correlationcomment=Correlation Comment
Report.identityfullname=Identity
Report.identitymail=Email
Report.internal=Internal Employee
report.idactive=Active Identity
Report.departure=Leave Date
Report.reconleavedate=Correlated Leave Date
Report.identityarrivaldate=Arrival Date
Report.joborg=Job Organization
Report.identityhrcode=HR Code
Report.groupdisplayname=Group Name
Report.groupdescription=Group Description
Report.groupsensitivity=Group Sensitivity Level
Report.groupsensitivityreason=Group Sensitivity Reason
Report.accountlogin=Account Login
Report.accountlastlogindate=Last Login Date
Report.username=User Name
Report.noownercode=Service/Technical Account
Report.repository=Group Repository
Report.reviewername=Reviewer Name
Report.reviewerorigin=Reviewer Origin
