iamapp=IAM App.
iamapp.code=IAM App. Code
iamapp.name=IAM App. Name
iamapp.sensitivity=IAM App. Sensitivity
iamapp.description=IAM App. Description
role=Role
role.code=Role Code
role.name=Role Name
role.sensitivity=Role Sensitivity
role.description=Role Description