#
#Thu Sep 17 18:14:32 CEST 2015
header.groupsearch=Group search
header.jobsearch=Job search
header.identitysearch=Identity search
header.organisationsearch=Organisation search
header.repositorysearch=Repository search
header.accountsearch=Account search
header.applicationsearch=Application Search
header.assetsearch=Asset search
library.title=<h2>Data Security Governance</h2>
header.permissionsearch=Permission search
SensitivityLevel=Sensitivity Level
SensitivityLevel.0=Not classified
SensitivityLevel.notclassified=Not classified
SensitivityLevel.na=Not classified
SensitivityLevel.1=Low
SensitivityLevel.low=Low
SensitivityLevel.2=Medium
SensitivityLevel.medium=Medium
SensitivityLevel.3=High
SensitivityLevel.high=High
SensitivityLevel.4=Highest
SensitivityLevel.extreme=Highest