#
#Mon May 06 14:52:28 CEST 2024
report.permissiondisplayname=Permission Name
report.reconcomment=User Reconciliation Comment
report.safedescription=Safe Description
report.identityinternal=Identity Internal
report.reconleavedate=User Owner Leave Date
report.permissioncode=Permission Code
report.identityfullame=Identity Fullname
report.accountlogin=User Login
report.identityarrivaldate=Identity Arrival Date
report.usertype=User Type
report.accountusername=Username
report.accountlastlogindate=User Last Login Date
report.identityhrcode=Identity Employee Number
report.reviewername=Reviewer Name
report.safesensitivitylevel=Safe Sensitivity Level
report.identityactive=Identity Active
report.identitydeparturedate=Identity Departure Date
report.identityjoborg=Identity Job and Organization
report.permissiondescription=Permission Description
report.permissionsensitivitylevel=Permission Sensitivity Level
report.identitymail=Identity Mail
report.reconnoownercode=Service User Code
report.safedisplayname=Safe
report.reviewerorigin=Reviewer Origin
